Repository tsparticles/tsparticles, pull requests merged in 2020-04, with the labels that each got.

#197 Fixed touch events
  README.md
  src/Classes/Particles.ts
  src/Classes/Utils/Constants.ts
  src/Classes/Utils/EventListeners.ts
Labels: bug, size/S

#198 improved polygon mask drawings
  schema/options.schema.json
  src/Classes/Canvas.ts
  src/Classes/Options/PolygonMask/Draw.ts
  src/Classes/Options/PolygonMask/PolygonMaskDrawStroke.ts
  src/Classes/PolygonMask.ts
  src/Classes/Utils/CanvasUtils.ts
  src/Classes/Utils/ColorUtils.ts
  src/Interfaces/Options/PolygonMask/IPolygonMaskDrawStroke.ts
Labels: bug, enhancement, size/L

#199 Removed presets, moved to their own repositories
  schema/options.schema.json
  src/Classes/Canvas.ts
  src/Classes/Container.ts
  src/Classes/Options/Options.ts
  src/Classes/Particle/Linker.ts
  src/Classes/Utils/CanvasUtils.ts
  src/Classes/Utils/ColorUtils.ts
  src/Classes/Utils/Constants.ts
  src/Classes/Utils/EventListeners.ts
  src/Classes/Utils/Presets.ts
  src/Classes/Utils/Utils.ts
  src/Enums/PresetType.ts
  src/Interfaces/Options/IOptions.ts
  src/Main.ts
Labels: dependencies, size/L

#200 fixed image shape drawer
  README.md
  demo/public/javascripts/presetFire.js
  demo/public/javascripts/shapeSpiral.js
  demo/views/index.pug
  src/Classes/ShapeDrawers/ImageDrawer.ts
  src/Main.ts
Labels: bug, size/S

#201 preventing issue with path2d, added types to package.json
  package.json
  src/Classes/PolygonMask.ts
Labels: size/S

#203 Release 1.12.1
  README.md
  demo/public/javascripts/shapeSpiral.js
  demo/views/index.html
  demo/views/index.pug
  package.json
  src/Classes/Canvas.ts
  src/Classes/Options/Particles/Particles.ts
  src/Classes/Options/Particles/Shape/Shape.ts
  src/Classes/ShapeDrawers/CircleDrawer.ts
  src/Classes/ShapeDrawers/HeartDrawer.ts
  src/Classes/ShapeDrawers/ImageDrawer.ts
  src/Classes/ShapeDrawers/LineDrawer.ts
  src/Classes/ShapeDrawers/PolygonDrawerBase.ts
  src/Classes/ShapeDrawers/SquareDrawer.ts
  src/Classes/ShapeDrawers/TextDrawer.ts
  src/Classes/Utils/CanvasUtils.ts
  src/Classes/Utils/ShapeUtils.ts
  src/Main.ts
  src/Types/ShapeDrawerFunction.ts
  tsParticles.nuspec
Labels: bug, size/L

#204 Release 1.12.1
  src/Main.ts
Labels: size/S

#209 Release 1.12.2 hotfix
  package-lock.json
  package.json
  src/Classes/Canvas.ts
  src/Classes/Utils/CanvasUtils.ts
  src/Main.ts
  tsParticles.nuspec
Labels: bug, size/XS

#210 Release 1.12.3
  package-lock.json
  package.json
  src/Classes/PolygonMask.ts
  src/Main.ts
  tsParticles.nuspec
Labels: bug, size/M

#211 hotfix 1.12.4
  demo/public/presets/reactBubbles.json
  demo/public/presets/reactMultipleImages.json
  demo/public/presets/reactNightSky.json
  demo/public/presets/reactPolygonMask.json
  demo/public/presets/reactSimple.json
  demo/public/presets/reactSnow.json
  demo/views/index.html
  demo/views/index.pug
  src/Classes/Utils/EventListeners.ts
  tsParticles.nuspec
  tsconfig.json
Labels: bug, size/XXL

#212 Release 1.12.4
  package-lock.json
  package.json
  src/index.ts
  webpack.config.js
Labels: size/XS

#213 1.12.5
  package-lock.json
  package.json
  src/index.ts
  tsParticles.nuspec
Labels: size/XS

#214 Hotfix react 1.12.6
  package-lock.json
  package.json
  src/Classes/Container.ts
  src/index.ts
  tsParticles.nuspec
  tsconfig.json
Labels: size/L

#218 Hotfix 1.12.7
  package-lock.json
  package.json
  src/Classes/Options/Particles/LineLinked.ts
  src/index.ts
  tsParticles.nuspec
Labels: bug, size/L

#222 Spatial grid for neighbor detection
  src/Classes/Particle.ts
  src/Classes/Particles.ts
  src/Classes/Utils/SpatialGrid.ts
Labels: size/L

#223 Release 1.12.9
  package-lock.json
  package.json
Labels: bug, size/XS

#224 Release 1.12.10
  demo/public/presets/destroy.json
  demo/views/index.html
  demo/views/index.pug
  package-lock.json
  package.json
  src/Classes/Particle/Updater.ts
  src/Classes/Utils/Utils.ts
  src/index.ts
  tsParticles.nuspec
Labels: bug, size/XXL

#228 Spatial updates, further integration
  src/Classes/Options/Particles/Shape/Shape.ts
  src/Classes/Particle.ts
  src/Classes/Particle/Attracter.ts
  src/Classes/Particle/Collider.ts
  src/Classes/Particle/InteractionManager.ts
  src/Classes/Particle/Linker.ts
  src/Classes/Particles.ts
  src/Classes/Utils/ColorUtils.ts
  src/Classes/Utils/SpatialGrid.ts
Labels: size/L

#230 Hotfix 1.12.11
  README.md
  package-lock.json
  package.json
  tsconfig.json
Labels: size/S

#232 Add Testing Structure and Tests for Utils.ts
  tests/Utils.ts
Labels: size/L

#234 Alpha 3 w/ multiple paths for polygon mask
  demo/public/images/loveknight.svg
  demo/public/presets/multiplePolygonMasks.json
  demo/public/presets/polygonMask.json
  demo/views/index.html
  demo/views/index.pug
  package-lock.json
  package.json
  schema/options.schema.json
  src/Classes/Canvas.ts
  src/Classes/Particles.ts
  src/Classes/PolygonMask.ts
  src/Classes/Utils/ColorUtils.ts
  src/Classes/Utils/SpatialGrid.ts
  src/Classes/Utils/Utils.ts
  src/Interfaces/IColor.ts
  src/Interfaces/ISvgPath.ts
  src/Interfaces/IValueColor.ts
  tests/ColorUtils.ts
  tests/Options.ts
  tests/Utils.ts
  tsParticles.nuspec
Labels: enhancement

#238 1.13.0 alpha 4
  demo/public/images/google.svg
  demo/public/presets/hollowknight.json
  demo/public/presets/multiplePolygonMasks.json
  demo/public/presets/polygonMask.json
  package-lock.json
  package.json
  src/Classes/PolygonMask.ts
  tsParticles.nuspec
Labels: size/M

#239 1.13.0 alpha 5
  package-lock.json
  package.json
  src/Classes/Container.ts
  src/Classes/Interactions/Mouse/Bubbler.ts
  src/Classes/Interactions/Mouse/Connecter.ts
  src/Classes/Interactions/Mouse/Grabber.ts
  src/Classes/Interactions/Mouse/Repulser.ts
  src/Classes/Interactions/Particles/Attracter.ts
  src/Classes/Interactions/Particles/Collider.ts
  src/Classes/Interactions/Particles/InteractionManager.ts
  src/Classes/Interactions/Particles/Linker.ts
  src/Classes/Particle.ts
  src/Classes/Particle/Bubbler.ts
  src/Classes/Particle/Grabber.ts
  src/Classes/Particle/Repulser.ts
  src/Classes/Particle/Updater.ts
  src/Classes/Particles.ts
  src/Classes/Utils/EventListeners.ts
  src/Classes/Utils/SpatialGrid.ts
  src/Interfaces/IRepulse.ts
  tsParticles.nuspec
Labels: size/XXL

#240 1.13.0 alpha 6
  package-lock.json
  package.json
  schema/options.schema.json
  src/Classes/Interactions/Mouse/Repulser.ts
  src/Classes/Options/Interactivity/Modes/Repulse.ts
  src/Interfaces/Options/Interactivity/Modes/IRepulse.ts
  tsParticles.nuspec
Labels: size/S

#243 Release 1.13.0 alpha 7
  demo/public/presets/multiplePolygonMasks.json
  package-lock.json
  package.json
  src/Classes/Canvas.ts
  src/Classes/Interactions/Particles/Linker.ts
  src/Classes/Particles.ts
  src/Classes/Utils/Constants.ts
  src/Classes/Utils/SpatialGrid.ts
  tsParticles.nuspec
Labels: bug, size/M

#244 Dev fix
  src/Classes/Options/Particles/Size/Size.ts
Labels: size/XS

#246 1.13.0-beta.0 version
  package-lock.json
  package.json
  src/Classes/Canvas.ts
  src/Classes/PolygonMask.ts
  src/Classes/Utils/CanvasUtils.ts
  src/Classes/Utils/SpatialGrid.ts
  src/Classes/Utils/Utils.ts
  tests/Utils.ts
  tsParticles.nuspec
Labels: bug, size/L

#248 1.13.0 beta 1
  demo/public/presets/test.json
  package-lock.json
  package.json
  src/Classes/Interactions/Particles/Attracter.ts
  src/Classes/Interactions/Particles/Collider.ts
  src/Classes/Interactions/Particles/Linker.ts
  tsParticles.nuspec
Labels: bug, size/L

#249 Add Tests for SpatialGrid.ts
  package-lock.json
  package.json
  tests/Fixture/TestContainer.ts
  tests/Fixture/TestParticle.ts
  tests/Fixture/TestSpatialGrid.ts
  tests/SpatialGrid.ts
Labels: size/XL

#252 new spatial grid tests
  package-lock.json
  package.json
  src/Classes/Emitter.ts
  src/Classes/PolygonMask.ts
  src/Classes/Utils/SpatialGrid.ts
  tests/Fixture/TestContainer.ts
  tests/Fixture/TestParticle.ts
  tests/Fixture/TestSpatialGrid.ts
  tests/SpatialGrid.ts
  tsParticles.nuspec
Labels: bug, enhancement, size/XL

#253 1.13.0 beta 4
  package-lock.json
  package.json
  src/Classes/Interactions/Particles/Collider.ts
  src/Classes/Particle.ts
  tsParticles.nuspec
Labels: bug, enhancement, size/M

#256 little fixes - beta 5
  README.md
  demo/public/presets/emitter.json
  package-lock.json
  package.json
  src/Classes/Emitter.ts
  src/Classes/Interactions/Mouse/Bubbler.ts
  src/Classes/Interactions/Mouse/Connecter.ts
  src/Classes/Interactions/Mouse/Grabber.ts
  src/Classes/Interactions/Mouse/Repulser.ts
  src/Classes/Interactions/Particles/Attracter.ts
  src/Classes/Interactions/Particles/Collider.ts
  src/Classes/Interactions/Particles/Linker.ts
  src/Classes/Options/Emitters/Emitter.ts
  src/Classes/Utils/SpatialGrid.ts
  src/Interfaces/IColor.ts
  src/Interfaces/ISvgPath.ts
  tsParticles.nuspec
Labels: size/L

#257 1.13.0 beta 6
  demo/public/presets/blackHoles.json
  demo/views/index.html
  demo/views/index.pug
  package-lock.json
  package.json
  schema/options.schema.json
  src/Classes/BlackHole.ts
  src/Classes/Canvas.ts
  src/Classes/Container.ts
  src/Classes/Interactions/Particles/Collider.ts
  src/Classes/Interactions/Particles/InteractionManager.ts
  src/Classes/Options/BlackHoles/BlackHole.ts
  src/Classes/Options/BlackHoles/BlackHoleRandomSize.ts
  src/Classes/Options/BlackHoles/BlackHoleSize.ts
  src/Classes/Options/Interactivity/Modes/Modes.ts
  src/Classes/Options/Options.ts
  src/Classes/Options/Particles/Collisions.ts
  src/Classes/Options/Particles/Move.ts
  src/Classes/Options/Particles/Particles.ts
  src/Classes/Particle.ts
  src/Classes/Particles.ts
  src/Classes/Utils/CanvasUtils.ts
  src/Classes/Utils/EventListeners.ts
  src/Enums/CollisionMode.ts
  src/Enums/Modes/ClickMode.ts
  src/Interfaces/Options/BlackHoles/IBlackHole.ts
  src/Interfaces/Options/BlackHoles/IBlackHoleRandomSize.ts
  src/Interfaces/Options/BlackHoles/IBlackHoleSize.ts
  src/Interfaces/Options/IOptions.ts
  src/Interfaces/Options/Interactivity/Modes/IModes.ts
  src/Interfaces/Options/Particles/ICollisions.ts
  src/Interfaces/Options/Particles/IMove.ts
  src/Interfaces/Options/Particles/IParticles.ts
  tests/Options.ts
  tsParticles.nuspec
Labels: documentation, enhancement, size/XXL

#259 1.13.0 Beta 8
  demo/public/presets/absorbers.json
  demo/views/index.html
  demo/views/index.pug
  package-lock.json
  package.json
  schema/options.schema.json
  src/Classes/Absorber.ts
  src/Classes/Canvas.ts
  src/Classes/Container.ts
  src/Classes/Emitter.ts
  src/Classes/Interactions/Mouse/Repulser.ts
  src/Classes/Options/Absorbers/Absorber.ts
  src/Classes/Options/Absorbers/AbsorberRandomSize.ts
  src/Classes/Options/Absorbers/AbsorberSize.ts
  src/Classes/Options/Interactivity/Modes/Modes.ts
  src/Classes/Options/Options.ts
  src/Classes/Particle.ts
  src/Classes/Particle/Updater.ts
  src/Classes/Particles.ts
  src/Classes/PolygonMask.ts
  src/Classes/Retina.ts
  src/Classes/Utils/CanvasUtils.ts
  src/Classes/Utils/EventListeners.ts
  src/Enums/Modes/ClickMode.ts
  src/Interfaces/Options/Absorbers/IAbsorber.ts
  src/Interfaces/Options/Absorbers/IAbsorberRandomSize.ts
  src/Interfaces/Options/Absorbers/IAbsorberSize.ts
  src/Interfaces/Options/BlackHoles/IBlackHoleSize.ts
  src/Interfaces/Options/IOptions.ts
  src/Interfaces/Options/Interactivity/Modes/IModes.ts
  tests/Utils.ts
  tsParticles.nuspec
Labels: bug, documentation, size/XL

#263 1.13.0 Beta 9
  demo/public/presets/dataImages.json
  demo/public/presets/twinkle.json
  demo/views/index.html
  demo/views/index.pug
  package-lock.json
  package.json
  schema/options.schema.json
  src/Classes/Canvas.ts
  src/Classes/Options/Particles/Particles.ts
  src/Classes/Options/Particles/Twinkle/Twinkle.ts
  src/Classes/Options/Particles/Twinkle/TwinkleValues.ts
  src/Classes/ShapeDrawers/ImageDrawer.ts
  src/Classes/Utils/EventListeners.ts
  src/Interfaces/Options/Particles/IParticles.ts
  src/Interfaces/Options/Particles/Twinkle/ITwinkle.ts
  src/Interfaces/Options/Particles/Twinkle/ITwinkleValues.ts
  tests/SpatialGrid.ts
  tests/Utils.ts
  tsParticles.nuspec
Labels: bug, documentation, enhancement, size/XL

#264 1.13.0 release
  package-lock.json
  package.json
  tsParticles.nuspec
Labels: size/XS

#267 Release 1.13.2
  package-lock.json
  package.json
  src/Classes/Emitter.ts
  src/Classes/Options/Emitters/Emitter.ts
  src/Classes/Options/Particles/Shape/Shape.ts
  src/Classes/Particle.ts
  src/Classes/Utils/EventListeners.ts
  src/Classes/Utils/Utils.ts
  tests/Options.ts
  tsParticles.nuspec
Labels: bug, size/L

#274 1.13.3
  demo/public/presets/absorbers.json
  demo/public/presets/big.json
  demo/public/presets/bubble.json
  demo/public/presets/collisions.json
  demo/public/presets/customPreset.json
  demo/public/presets/customShape.json
  demo/public/presets/dataImages.json
  demo/public/presets/default.json
  demo/public/presets/destroy.json
  demo/public/presets/divRepulse.json
  demo/public/presets/emitter.json
  demo/public/presets/emitterAbsorber.json
  demo/public/presets/fontawesome.json
  demo/public/presets/hollowknight.json
  demo/public/presets/nasa.json
  demo/public/presets/nyancat.json
  demo/public/presets/nyancat2.json
  demo/public/presets/polygons.json
  demo/public/presets/preset.json
  demo/public/presets/random.json
  demo/public/presets/slow.json
  demo/public/presets/snow.json
  demo/public/presets/star.json
  demo/public/presets/test.json
  demo/public/presets/trail.json
  demo/public/presets/twinkle.json
  package-lock.json
  package.json
  src/Classes/Options/Absorbers/Absorber.ts
  src/Classes/Options/Background/Background.ts
  src/Classes/Options/BackgroundMask/BackgroundMaskCover.ts
  src/Classes/Options/Interactivity/Modes/Bubble.ts
  src/Classes/Options/Particles/LineLinked/LineLinked.ts
  src/Classes/Options/Particles/LineLinked/LineLinkedShadow.ts
  src/Classes/Options/Particles/OptionsColor.ts
  src/Classes/Options/Particles/Particles.ts
  src/Classes/Options/Particles/Shadow.ts
  src/Classes/Options/Particles/Stroke.ts
  src/Classes/Options/Particles/Trail.ts
  src/Classes/Options/Particles/Twinkle/TwinkleValues.ts
  src/Classes/Options/PolygonMask/Draw.ts
  src/Classes/Options/PolygonMask/PolygonMaskDrawStroke.ts
  src/Classes/Particle/Updater.ts
  tsParticles.nuspec
Labels: size/XXL

#276 Hotfix 1.13.4
  package-lock.json
  package.json
  src/Classes/Emitter.ts
  tsParticles.nuspec
  tsconfig.browser.json
  tsconfig.json
  tsconfig.schema.json
  typedoc/themes/particles/assets/css/particles.css
  typedoc/themes/particles/assets/js/tsparticles.min.js
  typedoc/themes/particles/layouts/default.hbs
Labels: bug, documentation, size/L

#277 Release 1.13.5
  demo/public/presets/parallax.json
  demo/views/index.html
  demo/views/index.pug
  package-lock.json
  package.json
  src/Classes/Absorber.ts
  src/Classes/Canvas.ts
  src/Classes/Interactions/Mouse/Bubbler.ts
  src/Classes/Interactions/Mouse/Connector.ts
  src/Classes/Interactions/Particles/Attractor.ts
  src/Classes/Interactions/Particles/Collider.ts
  src/Classes/Interactions/Particles/Linker.ts
  src/Classes/Particle.ts
  src/Classes/Particle/Mover.ts
  src/Classes/Utils/CanvasUtils.ts
  src/Classes/Utils/SpatialGrid.ts
  tsParticles.nuspec
  typedoc/themes/particles/assets/js/tsparticles.min.js
Labels: bug
