Repository tsparticles/tsparticles, pull requests merged in 2020-03, with the labels that each got.

#94 Dev
  src/Classes/Options/Interactivity/Modes/Modes.ts
  src/Classes/Options/Interactivity/Modes/Slow.ts
  src/Classes/Particle.ts
  src/Classes/Particle/Bouncer.ts
  src/Classes/Particle/Bubbler.ts
  src/Classes/Particle/Grabber.ts
  src/Classes/Particle/Updater.ts
  src/Classes/Utils/Utils.ts
  src/Interfaces/Options/Interactivity/Modes/IOptionsInteractivityModes.ts
  src/Interfaces/Options/Interactivity/Modes/ISlow.ts
Labels: enhancement

#107 Preparing release 1.8.1
  demo/public/presets/collisions.json
  demo/views/index.html
  demo/views/index.pug
  package.json
  src/Classes/Drawer.ts
  src/Classes/Loader.ts
  src/Classes/Options/Interactivity/Events/DivEvent.ts
  src/Classes/Options/Interactivity/Events/Events.ts
  src/Classes/Options/Interactivity/Interactivity.ts
  src/Classes/Options/Interactivity/Modes/Connect.ts
  src/Classes/Options/Interactivity/Modes/Grab.ts
  src/Classes/Options/Interactivity/Modes/Modes.ts
  src/Classes/Options/Interactivity/Modes/Push.ts
  src/Classes/Options/Interactivity/Modes/Remove.ts
  src/Classes/Options/Options.ts
  src/Classes/Options/Particles/Attract.ts
  src/Classes/Options/Particles/Density.ts
  src/Classes/Options/Particles/Move.ts
  src/Classes/Options/Particles/Opacity.ts
  src/Classes/Options/Particles/OpacityAnimation.ts
  src/Classes/Options/Particles/Particles.ts
  src/Classes/Options/Particles/ParticlesSize.ts
  src/Classes/Options/Particles/ParticlesSizeAnimation.ts
  src/Classes/Options/Particles/Shape/ImageShape.ts
  src/Classes/Options/Particles/Shape/PolygonShape.ts
  src/Classes/Particle/Mover.ts
  src/Classes/Particle/Updater.ts
  src/Classes/Particles.ts
  src/Classes/Utils/Messages.ts
  src/Classes/Utils/Utils.ts
  src/Interfaces/Options/Interactivity/IInteractivity.ts
  src/Interfaces/Options/Interactivity/Modes/IModes.ts
  src/Interfaces/Options/Particles/IAttract.ts
  src/Main.ts
  tsParticles.nuspec
Labels: bug, enhancement

#109 collisions fix for 1.8.1
  demo/public/presets/collisions.json
  demo/public/presets/virus.json
  demo/views/index.html
  demo/views/index.pug
  package.json
  src/Classes/Drawer.ts
  src/Classes/Loader.ts
  src/Classes/Options/Interactivity/Events/DivEvent.ts
  src/Classes/Options/Interactivity/Events/Events.ts
  src/Classes/Options/Interactivity/Interactivity.ts
  src/Classes/Options/Interactivity/Modes/Connect.ts
  src/Classes/Options/Interactivity/Modes/Grab.ts
  src/Classes/Options/Interactivity/Modes/Modes.ts
  src/Classes/Options/Interactivity/Modes/Push.ts
  src/Classes/Options/Interactivity/Modes/Remove.ts
  src/Classes/Options/Options.ts
  src/Classes/Options/Particles/Attract.ts
  src/Classes/Options/Particles/Density.ts
  src/Classes/Options/Particles/Move.ts
  src/Classes/Options/Particles/Opacity.ts
  src/Classes/Options/Particles/OpacityAnimation.ts
  src/Classes/Options/Particles/Particles.ts
  src/Classes/Options/Particles/ParticlesSize.ts
  src/Classes/Options/Particles/ParticlesSizeAnimation.ts
  src/Classes/Options/Particles/Shape/ImageShape.ts
  src/Classes/Options/Particles/Shape/PolygonShape.ts
  src/Classes/Particle.ts
  src/Classes/Particle/Bouncer.ts
  src/Classes/Particle/Mover.ts
  src/Classes/Particle/Updater.ts
  src/Classes/Particles.ts
  src/Classes/Utils/Messages.ts
  src/Classes/Utils/Utils.ts
  src/Interfaces/Options/Interactivity/IInteractivity.ts
  src/Interfaces/Options/Interactivity/Modes/IModes.ts
  src/Interfaces/Options/Particles/IAttract.ts
  src/Main.ts
  tsParticles.nuspec
Labels: bug, enhancement

#114 Preparing release 1.8.2
  demo/public/presets/mask.json
  package.json
  src/Classes/Container.ts
  src/Classes/Options/PolygonMask/PolygonMask.ts
  src/Classes/Particle.ts
  src/Classes/Particle/Mover.ts
  src/Classes/Particle/Updater.ts
  src/Classes/Particles.ts
  src/Classes/PolygonMask.ts
  src/Enums/PolygonMaskInlineArrangement.ts
  src/Interfaces/Options/PolygonMask/IPolygonMask.ts
  src/Main.ts
  tsParticles.nuspec
Labels: bug, enhancement

#121 fix
  src/Classes/Utils/Utils.ts
Labels: bug

#123 fixed release 1.9.0
  package.json
  src/Classes/Options/Interactivity/Events/Events.ts
  src/Main.ts
  tsParticles.nuspec
Labels: bug

#125 Update Particle.ts
  package.json
  src/Classes/Particle.ts
  src/Main.ts
  tsParticles.nuspec
Labels: bug

#126 Preparing release 1.9.3
  README.md
  azure-pipelines.yml
  demo/public/presets/images.json
  demo/public/stylesheets/main.css
  demo/public/stylesheets/main.styl
  package.json
  src/Classes/Canvas.ts
  src/Classes/Container.ts
  src/Classes/Drawer.ts
  src/Classes/Options/Interactivity/Events/Events.ts
  src/Classes/Options/Particles/Rotate.ts
  src/Classes/Particle.ts
  src/Classes/Particle/Connecter.ts
  src/Classes/Particle/Drawer.ts
  src/Classes/Particle/Grabber.ts
  src/Classes/Particle/Linker.ts
  src/Classes/Particle/Updater.ts
  src/Classes/PolygonMask.ts
  src/Classes/Utils/CanvasUtils.ts
  src/Classes/Utils/ShapeUtils.ts
  src/Enums/RotateDirection.ts
  src/Main.ts
  tsParticles.nuspec
Labels: bug, enhancement

#127 Other features to 1.9.3
  README.md
  demo/public/presets/trail.json
  demo/views/index.html
  demo/views/index.pug
  src/Classes/Canvas.ts
  src/Classes/Container.ts
  src/Classes/Drawer.ts
  src/Classes/Options/Options.ts
  src/Classes/Options/Particles/Move.ts
  src/Classes/Options/Particles/Trail.ts
  src/Classes/Particle.ts
  src/Classes/Particle/Collider.ts
  src/Classes/Particle/InteractionManager.ts
  src/Classes/Particles.ts
  src/Interfaces/Options/IOptions.ts
  src/Interfaces/Options/Particles/IMove.ts
  src/Interfaces/Options/Particles/ITrail.ts
Labels: enhancement

#131 Hotfix 1.10.1
  package-lock.json
  package.json
  src/Classes/Container.ts
  src/Classes/Retina.ts
  src/Main.ts
  tsParticles.nuspec
Labels: bug

#137 Hotfix 1.10.3
  demo/public/presets/polygons.json
  demo/views/index.html
  demo/views/index.pug
  package-lock.json
  package.json
  src/Classes/Options/Particles/Shape/Shape.ts
Labels: bug

#138 Fix version bump 1.10.3
  package-lock.json
  package.json
  src/Main.ts
  tsParticles.nuspec
Labels: bug

#155 release 1.10.4
  package-lock.json
  package.json
  src/Classes/Options/PolygonMask/PolygonMaskDrawStroke.ts
  src/Main.ts
  tsParticles.nuspec
Labels: bug

#172 bubble mode fixed
  demo/public/presets/bubble.json
  package-lock.json
  package.json
  src/Classes/Particle/Bubbler.ts
Labels: bug

#181 Options JSON Schema and Destroy issue fixed
  demo/app.js
  demo/public/images/background2.jpg
  demo/public/images/background3.jpg
  demo/public/javascripts/demo.js
  demo/public/presets/background.json
  package-lock.json
  package.json
  schema/options.schema.json
  src/Classes/Container.ts
  src/Classes/Loader.ts
  src/Classes/Utils/Utils.ts
  src/Main.ts
Labels: bug, enhancement

#184 Release 1.11.1
  demo/public/javascripts/demo.js
  demo/public/stylesheets/main.css
  demo/public/stylesheets/main.styl
  demo/views/index.html
  demo/views/index.pug
  package-lock.json
  package.json
  src/Classes/Canvas.ts
  src/Classes/Container.ts
  src/Classes/Loader.ts
  src/Classes/Particle/Updater.ts
  src/Classes/Particles.ts
  src/Classes/PolygonMask.ts
  src/Classes/Utils/Utils.ts
  src/Main.ts
  tsParticles.nuspec
Labels: bug, size/L

#187 Release 1.11.2
  package-lock.json
  package.json
  src/Classes/Container.ts
  src/Classes/Particle.ts
  src/Classes/Particles.ts
  src/Classes/PolygonMask.ts
  src/Classes/Utils/EventListeners.ts
  src/Main.ts
  tsParticles.nuspec
Labels: bug, size/M
