Repository tsparticles/tsparticles, pull requests merged in 2020-09, with the labels that each got.

#830 Updating some links in the README
  README.md
Labels: size/S

#836 1.17.11
  components/angular/package.json
  components/angular/projects/ng-particles/package.json
  components/inferno/package.json
  components/jquery/package.json
  components/preact/package.json
  components/react/package.json
  components/svelte/package.json
  components/vue/package.json
  core/editor/package.json
  core/main/package.json
  core/main/src/Options/Classes/Particles/Opacity/OpacityRandom.ts
  core/main/tests/Options.ts
  core/main/tsParticles.nuspec
  demo/angular/package.json
  demo/editor/package.json
  demo/inferno/package.json
  demo/jquery/package.json
  demo/main/package.json
  demo/main/public/presets/test.json
  demo/preact/package.json
  demo/react/package.json
  demo/svelte/package.json
  demo/vue/package.json
  presets/60fps/package.json
  presets/backgroundMask/package.json
  presets/basic/package.json
  presets/bigCircles/package.json
  presets/bouncing/package.json
  presets/fire/package.json
  presets/fontAwesome/package.json
  presets/snow/package.json
  presets/stars/package.json
  shapes/bubble/package.json
  shapes/heart/package.json
  shapes/multiline-text/package.json
  shapes/spiral/package.json
  templates/react-ts/package.json
  templates/react-ts/template.json
  templates/react/package.json
  templates/react/template.json
Labels: size/L

#838 1.17.12
  components/angular/package.json
  components/angular/projects/ng-particles/package.json
  components/inferno/package.json
  components/jquery/package.json
  components/preact/package.json
  components/react/package.json
  components/svelte/package.json
  components/vue/package.json
  core/editor/package.json
  core/main/package.json
  core/main/src/Core/Canvas.ts
  core/main/src/Core/Container.ts
  core/main/tsParticles.nuspec
  demo/angular/package.json
  demo/editor/package.json
  demo/inferno/package.json
  demo/jquery/package.json
  demo/main/package.json
  demo/preact/package.json
  demo/react/package.json
  demo/svelte/package.json
  demo/vue/package.json
  presets/60fps/package.json
  presets/backgroundMask/package.json
  presets/basic/package.json
  presets/bigCircles/package.json
  presets/bouncing/package.json
  presets/fire/package.json
  presets/fontAwesome/package.json
  presets/snow/package.json
  presets/stars/package.json
  shapes/bubble/package.json
  shapes/heart/package.json
  shapes/multiline-text/package.json
  shapes/spiral/package.json
  templates/react-ts/package.json
  templates/react-ts/template.json
  templates/react/package.json
  templates/react/template.json
Labels: size/L

#851 build: updated nextTick to vue3 to use the new syntax
  components/vue3/package.json
  components/vue3/src/Particles/Particles.vue
  demo/vue3/package.json
  yarn.lock
Labels: size/S

#852 build: fixed vue3 tsconfig
  components/vue3/package.json
  components/vue3/tsconfig.json
  demo/vue3/package.json
Labels: size/XS

#889 docs: updated typedoc particles theme with motion handling
  .gitignore
  core/main/package.json
  yarn.lock
Labels: size/M
