Repository tsparticles/tsparticles, pull requests merged in 2020-07, with the labels that each got.

#490 Added multiline text shape
  shapes/tsparticles-shape-multiline-text/LICENSE
  shapes/tsparticles-shape-multiline-text/README.md
  shapes/tsparticles-shape-multiline-text/package.json
  shapes/tsparticles-shape-multiline-text/src/shape.ts
  shapes/tsparticles-shape-multiline-text/tsconfig.json
  shapes/tsparticles-shape-multiline-text/webpack.config.js
  yarn.lock
Labels: size/L

#511 fixed 1.17.0 color tests
  core/main/src/Utils/ColorUtils.ts
  core/main/tests/ColorUtils.ts
Labels: size/M

#518 fix: make it possible to use a canvas element
  core/tsparticles/src/Core/Loader.ts
Labels: size/XS

#519 fix: adds set method to main tsParticles instance. Closes #515
  core/tsparticles/package.json
  core/tsparticles/src/main.slim.ts
  core/tsparticles/tsParticles.nuspec
  demo/jquery-particles-demo/package.json
  demo/ng-particles-demo/package.json
  demo/particles.vue-demo/package.json
  demo/preact-particles-demo/package.json
  demo/react-tsparticles-demo/package.json
  demo/tsparticles-demo/package.json
  presets/tsparticles-preset-60fps/package.json
  presets/tsparticles-preset-backgroundMask/package.json
  presets/tsparticles-preset-basic/package.json
  presets/tsparticles-preset-bouncing/package.json
  presets/tsparticles-preset-fire/package.json
  presets/tsparticles-preset-fontAwesome/package.json
  presets/tsparticles-preset-snow/package.json
  presets/tsparticles-preset-stars/package.json
  shapes/tsparticles-shape-bubble/package.json
  shapes/tsparticles-shape-heart/package.json
  shapes/tsparticles-shape-multiline-text/package.json
  shapes/tsparticles-shape-spiral/package.json
  wrappers/jquery-particles/package.json
  wrappers/ng-particles/package.json
  wrappers/ng-particles/projects/ng-particles/package.json
  wrappers/particles.vue/package.json
  wrappers/preact-particles/package.json
  wrappers/react-tsparticles/package.json
Labels: size/L

#527 v1.17.0
  README.md
  components/angular/README.md
  components/angular/package.json
  components/jquery/README.md
  components/jquery/package.json
  components/preact/README.md
  components/preact/package.json
  components/react/README.md
  components/react/package.json
  components/svelte/README.md
  components/svelte/package.json
  components/svelte/rollup.config.js
  components/svelte/src/Particles.svelte
  components/svelte/src/main.js
  components/vue/README.md
  components/vue/package.json
  core/main/README.md
  core/main/package.json
  core/main/src/Core/Loader.ts
  core/main/src/main.slim.ts
  demo/angular/package.json
  demo/editor/package.json
  demo/jquery/package.json
  demo/main/package.json
  demo/preact/package.json
  demo/react/package.json
  demo/svelte/.gitignore
  demo/svelte/README.md
  demo/svelte/package.json
  demo/svelte/public/global.css
  demo/svelte/public/index.html
  demo/svelte/rollup.config.js
  demo/svelte/src/App.svelte
  demo/svelte/src/main.js
  demo/vue/package.json
  presets/60fps/package.json
  presets/backgroundMask/package.json
  presets/basic/package.json
  presets/bouncing/package.json
  presets/fire/package.json
  presets/fontAwesome/package.json
  presets/snow/package.json
  presets/stars/package.json
  shapes/bubble/package.json
  shapes/heart/package.json
  shapes/multiline-text/package.json
  shapes/spiral/package.json
  yarn.lock
Labels: documentation, enhancement, size/XXL

#551 Fix `linesOpacity` spelling and unify Vue examples
  README.md
  core/tsparticles/README.md
  wrappers/particles.vue/README.md
Labels: size/L

#564 1.17.0-beta.2
  components/angular/package.json
  components/angular/projects/ng-particles/package.json
  components/jquery/package.json
  components/preact/package.json
  components/react/package.json
  components/svelte/package.json
  components/vue/package.json
  core/editor/package.json
  core/main/package.json
  core/main/src/Core/Particle/Interactions/Mouse/Attractor.ts
  core/main/src/Core/Particle/Interactions/Mouse/Repulser.ts
  core/main/src/Core/Particle/Updater.ts
  core/main/tsParticles.nuspec
  demo/angular/package.json
  demo/editor/package.json
  demo/jquery/package.json
  demo/main/package.json
  demo/main/public/presets/plasma.json
  demo/main/views/index.html
  demo/main/views/index.pug
  demo/preact/package.json
  demo/react/package.json
  demo/svelte/package.json
  demo/vue/package.json
  presets/60fps/package.json
  presets/backgroundMask/package.json
  presets/basic/package.json
  presets/bouncing/package.json
  presets/fire/package.json
  presets/fontAwesome/package.json
  presets/snow/package.json
  presets/stars/package.json
  shapes/bubble/package.json
  shapes/heart/package.json
  shapes/multiline-text/package.json
  shapes/spiral/package.json
  yarn.lock
Labels: size/L

#565 other 1.17.0 fixes
  components/angular/package.json
  components/angular/projects/ng-particles/package.json
  components/jquery/package.json
  components/preact/package.json
  components/react/package.json
  components/svelte/package.json
  components/vue/package.json
  core/editor/package.json
  core/main/package.json
  core/main/src/Core/Particle.ts
  core/main/src/Core/Particles.ts
  core/main/tsParticles.nuspec
  demo/angular/package.json
  demo/editor/package.json
  demo/jquery/package.json
  demo/main/package.json
  demo/preact/package.json
  demo/react/package.json
  demo/svelte/package.json
  demo/vue/package.json
  presets/60fps/package.json
  presets/backgroundMask/package.json
  presets/basic/package.json
  presets/bouncing/package.json
  presets/fire/package.json
  presets/fontAwesome/package.json
  presets/snow/package.json
  presets/stars/package.json
  shapes/bubble/package.json
  shapes/heart/package.json
  shapes/multiline-text/package.json
  shapes/spiral/package.json
Labels: size/L

#577 Preparing 1.17.0 release
  components/jquery/src/particles.ts
  components/preact/index.d.ts
  components/react/index.d.ts
  core/main/src/Core/Container.ts
  core/main/src/Core/Loader.ts
  core/main/src/main.slim.ts
  core/main/src/pjs.ts
  core/main/tests/Fixture/TestContainer.ts
Labels: size/L

#610 Hotfix 1.17.2
  components/angular/package.json
  components/angular/projects/ng-particles/package.json
  components/inferno/package.json
  components/jquery/package.json
  components/preact/package.json
  components/react/package.json
  components/svelte/package.json
  components/vue/package.json
  core/editor/package.json
  core/main/package.json
  core/main/schema/options.schema.json
  core/main/src/Core/Particle.ts
  core/main/src/Options/Classes/Particles/Move/Move.ts
  core/main/src/Options/Classes/Particles/Move/MoveAngle.ts
  core/main/src/Options/Classes/Particles/Particles.ts
  core/main/src/Options/Interfaces/Particles/IParticles.ts
  core/main/src/Options/Interfaces/Particles/Move/IMove.ts
  core/main/src/Options/Interfaces/Particles/Move/IMoveAngle.ts
  core/main/src/Plugins/Emitters/EmitterInstance.ts
  core/main/tsParticles.nuspec
  demo/angular/package.json
  demo/editor/package.json
  demo/inferno/package.json
  demo/jquery/package.json
  demo/main/package.json
  demo/main/public/presets/emitterAngled.json
  demo/main/views/index.pug
  demo/preact/package.json
  demo/react/package.json
  demo/svelte/package.json
  demo/vue/package.json
  presets/60fps/package.json
  presets/backgroundMask/package.json
  presets/basic/package.json
  presets/bouncing/package.json
  presets/fire/package.json
  presets/fontAwesome/package.json
  presets/snow/package.json
  presets/stars/package.json
  shapes/bubble/package.json
  shapes/heart/package.json
  shapes/multiline-text/package.json
  shapes/spiral/package.json
  templates/react-ts/package.json
  templates/react-ts/template.json
  templates/react/package.json
  templates/react/template.json
Labels: size/L

#611 Hotfix 1.17.3
  components/angular/package.json
  components/angular/projects/ng-particles/package.json
  components/inferno/package.json
  components/jquery/package.json
  components/preact/package.json
  components/react/package.json
  components/svelte/package.json
  components/vue/package.json
  core/editor/package.json
  core/main/package.json
  core/main/src/Core/Interfaces/IParticle.ts
  core/main/src/Core/Particle.ts
  core/main/src/Core/Particle/Updater.ts
  core/main/src/Utils/CanvasUtils.ts
  core/main/tsParticles.nuspec
  demo/angular/package.json
  demo/editor/package.json
  demo/inferno/package.json
  demo/jquery/package.json
  demo/main/package.json
  demo/main/public/javascripts/demo.js
  demo/main/public/javascripts/noise.js
  demo/main/public/presets/noisePlanes.json
  demo/main/views/index.html
  demo/main/views/index.pug
  demo/preact/package.json
  demo/react/package.json
  demo/svelte/package.json
  demo/vue/package.json
  presets/60fps/package.json
  presets/backgroundMask/package.json
  presets/basic/package.json
  presets/bouncing/package.json
  presets/fire/package.json
  presets/fontAwesome/package.json
  presets/snow/package.json
  presets/stars/package.json
  shapes/bubble/package.json
  shapes/heart/package.json
  shapes/multiline-text/package.json
  shapes/spiral/package.json
  templates/react-ts/package.json
  templates/react-ts/template.json
  templates/react/package.json
  templates/react/template.json
Labels: size/XXL

#617 Hotfix 1.17.4
  components/angular/package.json
  components/angular/projects/ng-particles/package.json
  components/inferno/package.json
  components/jquery/package.json
  components/preact/package.json
  components/react/package.json
  components/svelte/package.json
  components/vue/package.json
  core/editor/package.json
  core/main/package.json
  core/main/src/Core/Canvas.ts
  core/main/tsParticles.nuspec
  demo/angular/package.json
  demo/editor/package.json
  demo/inferno/package.json
  demo/jquery/package.json
  demo/main/package.json
  demo/preact/package.json
  demo/react/package.json
  demo/svelte/package.json
  demo/vue/package.json
  presets/60fps/package.json
  presets/backgroundMask/package.json
  presets/basic/package.json
  presets/bouncing/package.json
  presets/fire/package.json
  presets/fontAwesome/package.json
  presets/snow/package.json
  presets/stars/package.json
  shapes/bubble/package.json
  shapes/heart/package.json
  shapes/multiline-text/package.json
  shapes/spiral/package.json
  templates/react-ts/package.json
  templates/react-ts/template.json
  templates/react/package.json
  templates/react/template.json
Labels: size/L

#620 v1.17.5
  components/angular/package.json
  components/angular/projects/ng-particles/package.json
  components/inferno/package.json
  components/jquery/package.json
  components/preact/package.json
  components/react/package.json
  components/svelte/README.md
  components/svelte/package.json
  components/svelte/rollup.config.js
  components/svelte/src/Particles.svelte
  components/svelte/src/index.js
  components/svelte/src/main.js
  components/vue/package.json
  core/editor/package.json
  core/main/package.json
  core/main/src/Core/Canvas.ts
  core/main/src/Utils/EventListeners.ts
  core/main/tsParticles.nuspec
  demo/angular/package.json
  demo/editor/package.json
  demo/inferno/package.json
  demo/jquery/package.json
  demo/main/package.json
  demo/main/public/presets/disappearing.json
  demo/main/views/index.html
  demo/main/views/index.pug
  demo/preact/package.json
  demo/react/package.json
  demo/svelte/package.json
  demo/vue/package.json
  presets/60fps/package.json
  presets/backgroundMask/package.json
  presets/basic/package.json
  presets/bouncing/package.json
  presets/fire/package.json
  presets/fontAwesome/package.json
  presets/snow/package.json
  presets/stars/package.json
  shapes/bubble/package.json
  shapes/heart/package.json
  shapes/multiline-text/package.json
  shapes/spiral/package.json
  templates/react-ts/package.json
  templates/react-ts/template.json
  templates/react/package.json
  templates/react/template.json
Labels: size/L
