Repository tsparticles/tsparticles, pull requests merged in 2020-05, with the labels that each got.

#282 Hotfix Issue #281
  .gitignore
  demo/public/report.html
  package-lock.json
  package.json
  src/Classes/Absorber.ts
  src/Classes/Particle.ts
  tsParticles.nuspec
  typedoc/themes/particles/assets/js/tsparticles.min.js
Labels: bug

#284 Add Particle Tests
  package-lock.json
  package.json
  tests/Fixture/TestCanvas.ts
  tests/Fixture/TestParticle.ts
  tests/Particle.ts
Labels: size/L

#290 Release 1.13.7
  package-lock.json
  package.json
  src/Classes/Container.ts
  src/Classes/FrameManager.ts
  src/Classes/Utils/EventListeners.ts
  tsParticles.nuspec
Labels: bug

#291 Update AbsorberSize.ts
  package-lock.json
  package.json
  src/Classes/FrameManager.ts
  src/Classes/Options/Absorbers/AbsorberSize.ts
  tsParticles.nuspec
Labels: size/S

#294 Hotfix 1.13.9
  package-lock.json
  package.json
  src/Classes/Container.ts
  src/Classes/Utils/EventListeners.ts
  tsParticles.nuspec
Labels: bug, size/S

#302 Test Particles
  tests/Fixture/TestParticles.ts
  tests/Particles.ts
Labels: size/L

#303 1.14.0
  package-lock.json
  package.json
  tsParticles.nuspec
Labels: size/XS

#314 Hotfix 1.14.1
  package-lock.json
  package.json
  src/Core/Particle.ts
  tsParticles.nuspec
Labels: size/XS

#319 Hotfix 1.14.2
  package-lock.json
  package.json
  src/Core/Particle/ShapeDrawers/ImageDrawer.ts
  tsParticles.nuspec
Labels: size/S

#330 Hotfix 1.14.3
  demo/public/images/biohazard.svg
  demo/public/images/canine.svg
  demo/public/presets/svgReplace.json
  demo/views/index.html
  demo/views/index.pug
  package-lock.json
  package.json
  src/Core/Interfaces/IImage.ts
  src/Core/Particle.ts
  src/Core/Particle/ShapeDrawers/ImageDrawer.ts
  src/Core/Particles.ts
  src/Options/Classes/Particles/Shape/ImageShape.ts
  src/Utils/Utils.ts
  tests/Options.ts
  tsParticles.nuspec
Labels: size/XXL

#337 1.15.0 beta updates
  package-lock.json
  package.json
  src/Core/Canvas.ts
  src/Core/Interfaces/IBubbleParticleData.ts
  src/Core/Interfaces/IParticle.ts
  src/Core/Particle.ts
  src/Core/Particle/Interactions/Mouse/Bubbler.ts
  src/Utils/CanvasUtils.ts
Labels: size/M

#338 Preparing 1.15.0 release
  package-lock.json
  package.json
  src/Core/Canvas.ts
  src/Core/Loader.ts
  src/Enums/MoveDirection.ts
  src/Enums/OutMode.ts
  src/Enums/PolygonMaskInlineArrangement.ts
  src/Enums/PolygonMaskMoveType.ts
  src/Enums/PolygonMaskType.ts
  src/Enums/ProcessBubbleType.ts
  src/Enums/RotateDirection.ts
  src/Enums/ShapeType.ts
  src/Interfaces/Options/IOptions.ts
  src/Plugins/Absorbers/Absorbers.ts
  src/Plugins/Absorbers/AbsorbersPlugin.ts
  src/Plugins/Absorbers/Enums/index.ts
  src/Plugins/Absorbers/Options/Interfaces/IAbsorberOptions.ts
  src/Plugins/Emitters/EmitterInstance.ts
  src/Plugins/Emitters/Emitters.ts
  src/Plugins/Emitters/EmittersPlugin.ts
  src/Plugins/Emitters/Enums/index.ts
  src/Plugins/Emitters/Options/Interfaces/IEmitterOptions.ts
  src/Plugins/PolygonMask/Enums/index.ts
  src/Plugins/PolygonMask/Options/Classes/LocalSvg.ts
  src/Plugins/PolygonMask/Options/Interfaces/IPolygonMaskOptions.ts
  src/Plugins/PolygonMask/PolygonMaskPlugin.ts
  src/Utils/CanvasUtils.ts
  tsParticles.nuspec
Labels: size/L

#342 Other fixes for 1.15.0 release
  .github/workflows/nodejs.yml
  README.md
  demo/public/presets/chars.json
  demo/views/index.html
  demo/views/index.pug
  package-lock.json
  package.json
  schema/options.schema.json
  src/Core/Canvas.ts
  src/Core/Container.ts
  src/Core/Interfaces/IPlugin.ts
  src/Options/Classes/Options.ts
  src/Plugins/Absorbers/AbsorbersPlugin.ts
  src/Plugins/Emitters/EmittersPlugin.ts
  src/Plugins/PolygonMask/PolygonMaskInstance.ts
  src/Plugins/PolygonMask/PolygonMaskPlugin.ts
  src/Utils/CanvasUtils.ts
  src/Utils/Plugins.ts
  src/Utils/Utils.ts
  src/index.slim.ts
  src/index.ts
  src/main.slim.ts
  src/main.ts
  src/pjs.ts
Labels: size/XL

#352 disabled codacy coverage reporter
  .github/workflows/nodejs.yml
Labels: size/S

#346 Set up CI with Azure Pipelines
  .github/workflows/tweet_issues.yml
  azure-pipelines-releases.yml
  azure-pipelines.yml
Labels: size/L

#354 fix bubble size on retina display
  demo/public/images/GitHub-Mark-120px-plus.png
  demo/public/images/GitHub_Logo.png
  demo/public/images/background2.jpg
  demo/public/images/biohazard.svg
  demo/public/images/canine.svg
  demo/public/images/google.svg
  demo/public/images/hollowknight.svg
  demo/public/images/loveknight.svg
  demo/public/images/smalldeer.svg
  package-lock.json
  package.json
  src/Core/Retina.ts
  tsParticles.nuspec
Labels: bug
