Repository tsparticles/tsparticles, pull requests merged in 2020-10, with the labels that each got.

#893 feat: add hsv color support
  core/main/src/Utils/ColorUtils.ts
Labels: size/S

#894 feat: hsv color documentation
  core/main/markdown/Color.md
Labels: size/S

#906 Fix link formatting, add jump link to the dependencies section
  README.md
Labels: size/XS

#907 Added Hindi translation.(Only Root READMe.md)
  traduction/README.hi.md
Labels: size/L

#911 Spanish translation of main readme and some docs
  core/main/traduction/README.es.md
  core/main/traduction/markdown/Color.md
  core/main/traduction/markdown/Container.md
  core/main/traduction/markdown/Options.md
  core/main/traduction/markdown/Plugins.md
  core/main/traduction/markdown/pjsMigration.md
  traduction/README.es.md
Labels: size/XL

#912 docs: added README translations to Russian
  components/angular/traduction/README.ru.md
  components/inferno/traduction/README.ru.md
  components/jquery/traduction/README.ru.md
  components/preact/traduction/README.ru.md
  components/react/traduction/README.ru.md
  components/svelte/traduction/README.ru.md
  components/vue/traduction/README.ru.md
  components/vue3/traduction/README.ru.md
  core/main/traduction/README.ru.md
  traduction/README.ru.md
Labels: size/XXL

#913 Updating staging with latest commits
  components/angular/traduction/README.ru.md
  components/inferno/traduction/README.ru.md
  components/jquery/traduction/README.ru.md
  components/preact/traduction/README.ru.md
  components/react/traduction/README.ru.md
  components/svelte/traduction/README.ru.md
  components/vue/traduction/README.ru.md
  components/vue3/traduction/README.ru.md
  core/main/traduction/README.ru.md
  traduction/README.ru.md
Labels: size/XXL

#916 Added Dutch translations
  components/angular/traduction/README.nl.md
  components/inferno/traduction/README.nl.md
  components/jquery/traduction/README.nl.md
  components/preact/traduction/README.nl.md
  components/react/traduction/README.nl.md
  components/svelte/traduction/README.nl.md
  components/vue/traduction/README.nl.md
  components/vue3/traduction/README.nl.md
  core/main/traduction/README.nl.md
  traduction/README.nl.md
Labels: size/XXL

#932 Add Indonesia translation
  traduction/README.id.md
Labels: size/L

#933 included German translation
  components/angular/traduction/README.de.md
  components/inferno/traduction/README.de.md
  components/jquery/traduction/README.de.md
  components/preact/traduction/README.de.md
  components/react/traduction/README.de.md
  components/svelte/traduction/README.de.md
  components/vue/traduction/README.de.md
  components/vue3/traduction/README.de.md
  traduction/README.de.md
Labels: size/XXL

#897 added the README translation to portuguese
  Traduction/README.pt-br.md
Labels: size/L

#937 1.18.2
  components/angular/package.json
  components/angular/projects/ng-particles/package.json
  components/inferno/package.json
  components/inferno/src/Particles.tsx
  components/jquery/package.json
  components/preact/package.json
  components/preact/src/Particles.tsx
  components/react/index.js
  components/react/package.json
  components/react/src/Particles.tsx
  components/svelte/package.json
  components/vue/package.json
  components/vue3/package.json
  core/editor/package.json
  core/main/package.json
  core/main/src/Interactions/External/Bouncer.ts
  core/main/tsParticles.nuspec
  demo/angular/package.json
  demo/editor/package.json
  demo/inferno/package.json
  demo/jquery/package.json
  demo/main/package.json
  demo/main/public/presets/snow.json
  demo/preact/package.json
  demo/react/package.json
  demo/svelte/package.json
  demo/vue/package.json
  demo/vue3/package.json
  presets/60fps/package.json
  presets/backgroundMask/package.json
  presets/basic/package.json
  presets/bigCircles/package.json
  presets/bouncing/package.json
  presets/fire/package.json
  presets/fontAwesome/package.json
  presets/fountain/package.json
  presets/snow/package.json
  presets/stars/package.json
  shapes/bubble/package.json
  shapes/heart/package.json
  shapes/multiline-text/package.json
  shapes/spiral/package.json
  templates/react-ts/package.json
  templates/react-ts/template.json
  templates/react/package.json
  templates/react/template.json
  yarn.lock
Labels: size/L

#940 1.18.3
  .github/dependabot.yml
  components/angular/package.json
  components/angular/projects/ng-particles/package.json
  components/inferno/package.json
  components/jquery/README.md
  components/jquery/package.json
  components/jquery/traduction/README.de.md
  components/jquery/traduction/README.nl.md
  components/jquery/traduction/README.ru.md
  components/preact/package.json
  components/react/package.json
  components/svelte/package.json
  components/vue/package.json
  components/vue3/package.json
  core/editor/package.json
  core/main/package.json
  core/main/src/Core/Retina.ts
  core/main/tsParticles.nuspec
  demo/angular/package.json
  demo/editor/package.json
  demo/inferno/package.json
  demo/jquery/package.json
  demo/main/package.json
  demo/preact/package.json
  demo/react/package.json
  demo/svelte/package.json
  demo/vue/package.json
  demo/vue3/package.json
  presets/60fps/package.json
  presets/backgroundMask/package.json
  presets/basic/package.json
  presets/bigCircles/package.json
  presets/bouncing/package.json
  presets/fire/package.json
  presets/fontAwesome/package.json
  presets/fountain/package.json
  presets/snow/package.json
  presets/stars/package.json
  shapes/bubble/package.json
  shapes/heart/package.json
  shapes/multiline-text/package.json
  shapes/spiral/package.json
  templates/react-ts/package.json
  templates/react-ts/template.json
  templates/react/package.json
  templates/react/template.json
Labels: size/L

#948 1.18.4
  components/angular/package.json
  components/angular/projects/ng-particles/package.json
  components/inferno/package.json
  components/inferno/tsconfig.json
  components/jquery/package.json
  components/preact/package.json
  components/preact/tsconfig.json
  components/react/package.json
  components/react/tsconfig.json
  components/svelte/package.json
  components/vue/package.json
  components/vue3/package.json
  core/editor/package.json
  core/editor/src/Sections/Options/OptionsEditor.ts
  core/editor/tsconfig.json
  core/main/markdown/Options.md
  core/main/package.json
  core/main/schema/options.schema.json
  core/main/scripts/install.js
  core/main/src/Core/Container.ts
  core/main/src/Core/Retina.ts
  core/main/src/Options/Classes/Options.ts
  core/main/src/Options/Interfaces/IOptions.ts
  core/main/tests/Options.ts
  core/main/tsParticles.nuspec
  demo/angular/package.json
  demo/editor/package.json
  demo/inferno/package.json
  demo/jquery/package.json
  demo/jquery/public/presets/fontawesome.json
  demo/jquery/public/presets/trail.json
  demo/main/package.json
  demo/preact/package.json
  demo/react/package.json
  demo/svelte/package.json
  demo/vue/package.json
  demo/vue3/package.json
  presets/60fps/package.json
  presets/backgroundMask/package.json
  presets/basic/package.json
  presets/bigCircles/package.json
  presets/bouncing/package.json
  presets/fire/package.json
  presets/fontAwesome/package.json
  presets/fountain/package.json
  presets/snow/package.json
  presets/stars/package.json
  shapes/bubble/package.json
  shapes/heart/package.json
  shapes/multiline-text/package.json
  shapes/spiral/package.json
  templates/react-ts/package.json
  templates/react-ts/template.json
  templates/react-ts/template/tsconfig.json
  templates/react/package.json
  templates/react/template.json
  yarn.lock
Labels: size/XL

#961 1.18.5
  README.md
  components/angular/package.json
  components/angular/projects/ng-particles/package.json
  components/inferno/package.json
  components/jquery/package.json
  components/preact/package.json
  components/react/package.json
  components/svelte/package.json
  components/vue/package.json
  components/vue3/README.md
  components/vue3/package.json
  core/editor/package.json
  core/main/package.json
  core/main/scripts/install.js
  core/main/src/Utils/ColorUtils.ts
  core/main/tests/Themes.ts
  core/main/tsParticles.nuspec
  core/main/tsconfig.base.json
  core/main/tsconfig.json
  demo/angular/package.json
  demo/editor/package.json
  demo/inferno/package.json
  demo/jquery/package.json
  demo/main/package.json
  demo/preact/package.json
  demo/react/package.json
  demo/svelte/package.json
  demo/vue/package.json
  demo/vue3/package.json
  presets/60fps/package.json
  presets/backgroundMask/package.json
  presets/basic/package.json
  presets/bigCircles/package.json
  presets/bouncing/package.json
  presets/fire/package.json
  presets/fontAwesome/package.json
  presets/fountain/package.json
  presets/snow/package.json
  presets/stars/package.json
  shapes/bubble/package.json
  shapes/heart/package.json
  shapes/multiline-text/package.json
  shapes/spiral/package.json
  templates/react-ts/package.json
  templates/react-ts/template.json
  templates/react/package.json
  templates/react/template.json
  yarn.lock
Labels: size/XXL

#976 test(main): add test for getParticleBaseVelocity
  core/main/tests/Utils.ts
Labels: size/M

#980 test(main): add test for loadImage
  core/main/tests/Utils.ts
Labels: size/M

#983 test(main): add test for getAvailablePlugins
  core/main/tests/Utils.ts
Labels: size/M

#987 test(main): add test for downloadSvgImage
  core/main/tests/Utils.ts
Labels: size/M

#989 add spanish translate readme
  traduction/README.es.md
Labels: size/L

#990 1.18.8
  components/angular/package.json
  components/angular/projects/ng-particles/package.json
  components/inferno/package.json
  components/jquery/package.json
  components/preact/package.json
  components/react/package.json
  components/svelte/package.json
  components/vue/package.json
  components/vue3/package.json
  core/editor/package.json
  core/main/package.json
  core/main/src/Interactions/Particles/Attractor.ts
  core/main/tsParticles.nuspec
  demo/angular/package.json
  demo/editor/package.json
  demo/inferno/package.json
  demo/jquery/package.json
  demo/main/package.json
  demo/preact/package.json
  demo/react/package.json
  demo/svelte/package.json
  demo/vue/package.json
  demo/vue3/package.json
  presets/60fps/package.json
  presets/backgroundMask/package.json
  presets/basic/package.json
  presets/bigCircles/package.json
  presets/bouncing/package.json
  presets/fire/package.json
  presets/fontAwesome/package.json
  presets/fountain/package.json
  presets/snow/package.json
  presets/stars/package.json
  shapes/bubble/package.json
  shapes/heart/package.json
  shapes/multiline-text/package.json
  shapes/spiral/package.json
  templates/react-ts/package.json
  templates/react-ts/template.json
  templates/react/package.json
  templates/react/template.json
Labels: size/L

#991 Docs Fix
  components/inferno/tsconfig.json
  components/jquery/tsconfig.json
  components/preact/tsconfig.json
  components/react/tsconfig.json
  components/vue/tsconfig.json
  components/vue3/tsconfig.json
  core/editor/tsconfig.json
  core/main/markdown/Options/Infection.md
  core/main/markdown/Options/Particles.md
  core/main/tsconfig.json
  demo/preact/package.json
  demo/react/tsconfig.json
  presets/60fps/tsconfig.json
  presets/backgroundMask/tsconfig.json
  presets/basic/tsconfig.json
  presets/bigCircles/tsconfig.json
  presets/bouncing/tsconfig.json
  presets/fire/tsconfig.json
  presets/fontAwesome/tsconfig.json
  presets/fountain/tsconfig.json
  presets/snow/tsconfig.json
  presets/stars/tsconfig.json
  shapes/bubble/tsconfig.json
  shapes/heart/tsconfig.json
  shapes/multiline-text/tsconfig.json
  shapes/spiral/tsconfig.json
Labels: size/L
