Repository tsparticles/tsparticles, pull requests merged in 2020-11, with the labels that each got.

#992 feat: add z-index option to Particles, renders particles in that order
  core/main/markdown/Options/Particles/ZIndex.md
  core/main/src/Core/Particle.ts
  core/main/src/Options/Classes/Particles/Particles.ts
  core/main/src/Options/Classes/Particles/ZIndex/ZIndex.ts
  core/main/src/Options/Interfaces/Particles/IParticles.ts
  core/main/src/Options/Interfaces/Particles/ZIndex/IZIndex.ts
  demo/main/public/presets/zIndex.json
Labels: hacktoberfest-accepted, size/L

#997 1.18.9
  components/angular/package.json
  components/angular/projects/ng-particles/package.json
  components/inferno/package.json
  components/jquery/package.json
  components/preact/package.json
  components/react/package.json
  components/svelte/package.json
  components/vue/package.json
  components/vue3/package.json
  core/editor/package.json
  core/main/package.json
  core/main/src/Core/Particle/Mover.ts
  core/main/src/Core/Retina.ts
  core/main/src/Interactions/Particles/Linker.ts
  core/main/tsParticles.nuspec
  demo/angular/package.json
  demo/editor/package.json
  demo/inferno/package.json
  demo/jquery/package.json
  demo/main/package.json
  demo/preact/package.json
  demo/react/package.json
  demo/svelte/package.json
  demo/vue/package.json
  demo/vue3/package.json
  presets/60fps/package.json
  presets/backgroundMask/package.json
  presets/basic/package.json
  presets/bigCircles/package.json
  presets/bouncing/package.json
  presets/fire/package.json
  presets/fontAwesome/package.json
  presets/fountain/package.json
  presets/snow/package.json
  presets/stars/package.json
  shapes/bubble/package.json
  shapes/heart/package.json
  shapes/multiline-text/package.json
  shapes/spiral/package.json
  templates/react-ts/package.json
  templates/react-ts/template.json
  templates/react/package.json
  templates/react/template.json
Labels: size/L

#993 feat: add repulse to particles
  core/main/src/Core/Particle/InteractionManager.ts
  core/main/src/Core/Particle/Mover.ts
  core/main/src/Core/Particles.ts
  core/main/src/Interactions/External/Repulser.ts
  core/main/src/Interactions/Particles/Collider.ts
  core/main/src/Interactions/Particles/Repulser.ts
  core/main/src/Options/Classes/Particles/Particles.ts
  core/main/src/Options/Classes/Particles/Repulse/Repulse.ts
  core/main/src/Options/Interfaces/Particles/IParticles.ts
  core/main/src/Options/Interfaces/Particles/Repulse/IRepulse.ts
  demo/main/public/presets/repulse.json
  demo/main/views/index.pug
Labels: hacktoberfest-accepted, size/L

#1000 GitHub templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/custom.md
Labels: size/M

#986 feat: add static orbit
  core/main/src/Core/Canvas.ts
  core/main/src/Core/Interfaces/IOrbit.ts
  core/main/src/Core/Interfaces/IParticle.ts
  core/main/src/Core/Particle.ts
  core/main/src/Core/Particle/Updater.ts
  core/main/src/Core/Retina.ts
  core/main/src/Enums/OrbitType.ts
  core/main/src/Options/Classes/Particles/Orbit/Orbit.ts
  core/main/src/Options/Classes/Particles/Orbit/OrbitAnimation.ts
  core/main/src/Options/Classes/Particles/Orbit/OrbitRotation.ts
  core/main/src/Options/Classes/Particles/Particles.ts
  core/main/src/Options/Interfaces/Particles/IParticles.ts
  core/main/src/Options/Interfaces/Particles/Orbit/IOrbit.ts
  core/main/src/Options/Interfaces/Particles/Orbit/IOrbitAnimation.ts
  core/main/src/Options/Interfaces/Particles/Orbit/IOrbitRotation.ts
  core/main/src/Utils/CanvasUtils.ts
  demo/main/public/presets/orbit.json
  demo/main/views/index.pug
Labels: hacktoberfest-accepted, size/L

#1025 Update Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/S
