Repository tsparticles/tsparticles, pull requests merged in 2021-03, with the labels that each got.

#1347 1.19.1
  .github/workflows/codeql-analysis.yml
  components/angular/package.json
  components/angular/projects/ng-particles/package.json
  components/inferno/package.json
  components/jquery/package.json
  components/preact/package.json
  components/react/package.json
  components/svelte/package.json
  components/vue/package.json
  components/vue3/package.json
  core/editor/package.json
  core/main/package.json
  core/main/tsParticles.nuspec
  demo/angular/package.json
  demo/editor/package.json
  demo/inferno/package.json
  demo/jquery/package.json
  demo/main/package.json
  demo/preact/package.json
  demo/react/package.json
  demo/svelte/package.json
  demo/vue/package.json
  demo/vue3/package.json
  presets/60fps/package.json
  presets/backgroundMask/package.json
  presets/basic/package.json
  presets/bigCircles/package.json
  presets/bouncing/package.json
  presets/fire/package.json
  presets/fontAwesome/package.json
  presets/fountain/package.json
  presets/snow/package.json
  presets/stars/package.json
  shapes/bubble/package.json
  shapes/heart/package.json
  shapes/multiline-text/package.json
  shapes/spiral/package.json
  templates/react-ts/package.json
  templates/react-ts/template.json
  templates/react/package.json
  templates/react/template.json
  website/package.json
Labels: size/L

#1355 GH Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/M

#1376 1.20.1
  components/angular/package.json
  components/angular/projects/ng-particles/package.json
  components/inferno/package.json
  components/jquery/package.json
  components/preact/package.json
  components/react/package.json
  components/svelte/package.json
  components/vue/package.json
  components/vue3/package.json
  core/editor/package.json
  core/main/package.json
  core/main/src/Core/Interfaces/IContainerPlugin.ts
  core/main/src/Core/Particles.ts
  core/main/src/Plugins/Emitters/EmitterInstance.ts
  core/main/src/Plugins/Emitters/Emitters.ts
  core/main/tsParticles.nuspec
  demo/angular/package.json
  demo/editor/package.json
  demo/inferno/package.json
  demo/jquery/package.json
  demo/main/package.json
  demo/preact/package.json
  demo/react/package.json
  demo/svelte/package.json
  demo/vue/package.json
  demo/vue3/package.json
  presets/60fps/package.json
  presets/backgroundMask/package.json
  presets/basic/package.json
  presets/bigCircles/package.json
  presets/bouncing/package.json
  presets/bubbles/package.json
  presets/fire/package.json
  presets/fontAwesome/package.json
  presets/fountain/package.json
  presets/snow/package.json
  presets/stars/package.json
  shapes/bubble/package.json
  shapes/heart/package.json
  shapes/multiline-text/package.json
  shapes/spiral/package.json
  templates/react-ts/package.json
  templates/react-ts/template.json
  templates/react/package.json
  templates/react/template.json
  website/package.json
Labels: size/L

#1395 build: website updates
  website/404.html
  website/index.html
  website/js/demo.js
  website/js/demo.min.js
  website/samples/index.html
Labels: size/XL

#1399 1.22.1
  components/angular/package.json
  components/angular/projects/ng-particles/package.json
  components/inferno/package.json
  components/jquery/package.json
  components/preact/package.json
  components/react/package.json
  components/svelte/package.json
  components/vue/package.json
  components/vue3/package.json
  core/editor/package.json
  core/main/package.json
  core/main/src/Core/Particle/Updater.ts
  core/main/tsParticles.nuspec
  demo/angular/package.json
  demo/editor/package.json
  demo/inferno/package.json
  demo/jquery/package.json
  demo/main/package.json
  demo/main/public/presets/hyperspace.json
  demo/main/views/index.pug
  demo/preact/package.json
  demo/react/package.json
  demo/svelte/package.json
  demo/vue/package.json
  demo/vue3/package.json
  presets/60fps/package.json
  presets/backgroundMask/package.json
  presets/basic/package.json
  presets/bigCircles/package.json
  presets/bouncing/package.json
  presets/bubbles/package.json
  presets/fire/package.json
  presets/fontAwesome/package.json
  presets/fountain/package.json
  presets/seaAnemone/package.json
  presets/snow/package.json
  presets/stars/package.json
  shapes/bubble/package.json
  shapes/confetti/package.json
  shapes/heart/package.json
  shapes/multiline-text/package.json
  shapes/rounded-rect/package.json
  shapes/spiral/package.json
  templates/react-ts/package.json
  templates/react-ts/template.json
  templates/react/package.json
  templates/react/template.json
  website/package.json
Labels: size/L

#1406 build: website updated
  website/404.html
  website/configs/index.json
  website/index.html
  website/js/demo.js
  website/js/demo.min.js
  website/presets/big.json
  website/presets/confetti.json
  website/presets/multiplePolygonMasks.json
  website/samples/index.html
Labels: size/L

#1411 build: website updated
  website/404.html
  website/index.html
  website/js/demo.js
  website/js/demo.min.js
  website/samples/index.html
Labels: size/M

#1413 React 1.24.2
  components/react/package.json
  components/react/src/Particles.tsx
  demo/react/package.json
  templates/react-ts/package.json
  templates/react-ts/template.json
  templates/react/package.json
  templates/react/template.json
  website/package.json
Labels: size/S
