Repository tsparticles/tsparticles, pull requests merged in 2021-02, with the labels that each got.

#1289 V1 updates
  .github/workflows/tweet_issues.yml
  components/angular/package.json
  components/angular/projects/ng-particles/package.json
  components/inferno/package.json
  components/jquery/package.json
  components/preact/package.json
  components/react/package.json
  components/svelte/package.json
  components/vue/package.json
  components/vue3/package.json
  core/editor/package.json
  core/main/package.json
  core/main/tsParticles.nuspec
  demo/angular/package.json
  demo/editor/package.json
  demo/inferno/package.json
  demo/jquery/package.json
  demo/main/package.json
  demo/preact/package.json
  demo/react/package.json
  demo/svelte/package.json
  demo/vue/package.json
  demo/vue3/package.json
  presets/60fps/package.json
  presets/backgroundMask/package.json
  presets/basic/package.json
  presets/bigCircles/package.json
  presets/bouncing/package.json
  presets/fire/package.json
  presets/fontAwesome/package.json
  presets/fountain/package.json
  presets/snow/package.json
  presets/stars/package.json
  shapes/bubble/package.json
  shapes/heart/package.json
  shapes/multiline-text/package.json
  shapes/spiral/package.json
  templates/react-ts/package.json
  templates/react-ts/template.json
  templates/react/package.json
  templates/react/template.json
  website/package.json
Labels: size/L

#1314 Website updates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  website/404.html
  website/index.html
  website/js/demo.js
  website/js/demo.min.js
  website/samples/index.html
Labels: size/XXL

#1326 Update README.md
  README.md
Labels: size/XS
