Repository tsparticles/tsparticles, pull requests merged in 2021-11, with the labels that each got.

#2434 Added Turkish translation of the principal README
  traduction/README.tr.md
Labels: size/L

#2470 build: website updated to 1.37.3
  website/404.html
  website/index.html
  website/js/demo.js
  website/samples/index.html
  website/samples/presets/bigCircles.html
  website/samples/presets/bubbles.html
  website/samples/presets/confetti.html
  website/samples/presets/fire.html
  website/samples/presets/firefly.html
  website/samples/presets/fireworks.html
  website/samples/presets/fountain.html
  website/samples/presets/links.html
  website/samples/presets/seaAnemone.html
  website/samples/presets/snow.html
  website/samples/presets/stars.html
  website/samples/presets/triangles.html
Labels: size/L

#2474 typedoc updated
  engine/package.json
  engine/tsconfig.json
  engine/typedoc-theme/partials/analytics.hbs
  engine/yarn.lock
  lerna.json
  utils/typedoc-theme/.eslintignore
  utils/typedoc-theme/.eslintrc.js
  utils/typedoc-theme/.prettierrc
  utils/typedoc-theme/README.md
  utils/typedoc-theme/package.dist.json
  utils/typedoc-theme/package.json
  utils/typedoc-theme/scripts/distfiles.js
  utils/typedoc-theme/src/index.tsx
  utils/typedoc-theme/src/theme.tsx
  utils/typedoc-theme/tsconfig.json
  utils/typedoc-theme/yarn.lock
Labels: size/XXL

#2544 Website Updates
  demo/react/package.json
  demo/react/yarn.lock
  package.json
  utils/typedoc-theme/package.dist.json
  website/404.html
  website/index.html
  website/js/demo.js
  website/samples/index.html
  website/samples/presets/bigCircles.html
  website/samples/presets/bubbles.html
  website/samples/presets/confetti.html
  website/samples/presets/fire.html
  website/samples/presets/firefly.html
  website/samples/presets/fireworks.html
  website/samples/presets/fountain.html
  website/samples/presets/links.html
  website/samples/presets/seaAnemone.html
  website/samples/presets/snow.html
  website/samples/presets/stars.html
  website/samples/presets/triangles.html
  yarn.lock
Labels: size/XXL

#2554 build: reverted broken typedoc theme
  engine/tsconfig.json
  utils/typedoc-theme/src/index.tsx
Labels: size/S
