Repository tsparticles/tsparticles, pull requests merged in 2021-08, with the labels that each got.

#1937 Issue Forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/custom.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: size/L

#1966 Readme updates
  README.md
  website/images/premium-addons-wordpress-plugin.png
  website/index.html
Labels: size/L

#1977 Update nodejs.yml
  .github/workflows/nodejs.yml
Labels: size/XS

#1984 Readme updates
  website/images/amongus_blue.png
  website/images/amongus_cyan.png
  website/images/amongus_green.png
  website/images/amongus_lime.png
  website/images/amongus_orange.png
  website/images/amongus_pink.png
  website/images/amongus_red.png
  website/images/amongus_white.png
Labels: size/XS

#1986 Ads
  components/vue3/yarn.lock
  website/404.html
  website/ads.txt
  website/images/presets/bigCircles.png
  website/images/presets/bubbles.png
  website/images/presets/confetti.png
  website/images/presets/fire.png
  website/images/presets/firefly.png
  website/images/presets/fireworks.png
  website/images/presets/fountain.png
  website/images/presets/links.png
  website/images/presets/seaAnemone.png
  website/images/presets/snow.png
  website/images/presets/stars.png
  website/index.html
  website/samples/index.html
  website/samples/presets/bigCircles.html
  website/samples/presets/bubbles.html
  website/samples/presets/confetti.html
  website/samples/presets/fire.html
  website/samples/presets/firefly.html
  website/samples/presets/fireworks.html
  website/samples/presets/fountain.html
  website/samples/presets/index.html
  website/samples/presets/links.html
  website/samples/presets/seaAnemone.html
  website/samples/presets/snow.html
  website/samples/presets/stars.html
  website/sitemap.xml
Labels: size/XXL

#2007 Website Google Analytics updates
  website/samples/presets/bigCircles.html
  website/samples/presets/bubbles.html
  website/samples/presets/confetti.html
  website/samples/presets/fire.html
  website/samples/presets/firefly.html
  website/samples/presets/fireworks.html
  website/samples/presets/fountain.html
  website/samples/presets/index.html
  website/samples/presets/links.html
  website/samples/presets/seaAnemone.html
  website/samples/presets/snow.html
  website/samples/presets/stars.html
Labels: size/L

#2014 Typedoc theme
  components/inferno/yarn.lock
  engine/package.json
  engine/typedoc-theme/partials/analytics.hbs
  website/index.html
Labels: size/M

#2015 Added privacy to website
  website/privacy.html
Labels: size/M

#2019 Update renovate.json
  renovate.json
Labels: size/XS

#2026 Update renovate.json
  renovate.json
Labels: size/XS
