Repository tsparticles/tsparticles, pull requests merged in 2021-10, with the labels that each got.

#2277 changed react/README.md example code into modern one
  components/react/README.md
  components/react/traduction/README.de.md
  components/react/traduction/README.nl.md
  components/react/traduction/README.pt-br.md
  components/react/traduction/README.ru.md
Labels: size/XL, hacktoberfest-accepted

#2281 completed incomplete codes in react/readme in other languages
  components/react/traduction/README.de.md
  components/react/traduction/README.mn.md
  components/react/traduction/README.nl.md
  components/react/traduction/README.pt-br.md
  components/react/traduction/README.ru.md
Labels: size/L

#2279 Add unit test for color utils
  engine/src/Utils/ColorUtils.ts
  engine/tests/ColorUtils.ts
Labels: size/M

#2282 Translated readme.md to mongolian language in angular
  components/angular/traduction/README.mn.md
  components/react/traduction/README.de.md
  components/react/traduction/README.mn.md
  components/react/traduction/README.nl.md
  components/react/traduction/README.pt-br.md
  components/react/traduction/README.ru.md
Labels: size/L, hacktoberfest-accepted

#2284 fix(website): not loading font awesome script
  components/angular/traduction/README.mn.md
  components/react/traduction/README.mn.md
  website/samples/index.html
Labels: size/L

#2285 Fix Preset not scrollable in website demo page
  website/css/main.css
  website/css/main.css.map
  website/css/main.min.css
  website/css/main.scss
  website/samples/index.html
Labels: size/S

#2286 Update it README.md
  README.md
Labels: size/S

#2287 Website updated
  engine/typedoc-theme/partials/analytics.hbs
  website/404.html
  website/index.html
  website/samples/index.html
  website/samples/presets/bigCircles.html
  website/samples/presets/bubbles.html
  website/samples/presets/confetti.html
  website/samples/presets/fire.html
  website/samples/presets/firefly.html
  website/samples/presets/fireworks.html
  website/samples/presets/fountain.html
  website/samples/presets/index.html
  website/samples/presets/links.html
  website/samples/presets/seaAnemone.html
  website/samples/presets/snow.html
  website/samples/presets/stars.html
  website/samples/presets/triangles.html
Labels: size/L

#2289 Fix anchors.
  README.md
Labels: size/M

#2290 Readme Updates
  README.md
Labels: size/M, hacktoberfest-accepted

#2291 Update README.md
  README.md
Labels: size/XS

#2299 Changes in website present page
  website/samples/presets/index.html
Labels: size/L
