Repository tsparticles/tsparticles, pull requests merged in 2022-02, with the labels that each got.

#3246 Deps Updates
  components/inferno/yarn.lock
  components/preact/yarn.lock
  components/react/yarn.lock
  components/riot/yarn.lock
  components/solid/yarn.lock
  demo/ionic/package.json
  demo/ionic/yarn.lock
  editor/yarn.lock
  interactions/light/yarn.lock
  interactions/particles/repulse/yarn.lock
  paths/curves/yarn.lock
  paths/perlinNoise/yarn.lock
  paths/polygon/yarn.lock
  paths/simplexNoise/yarn.lock
  plugins/infection/yarn.lock
  presets/bigCircles/yarn.lock
  presets/bubbles/yarn.lock
  presets/confetti/yarn.lock
  presets/fire/yarn.lock
  presets/firefly/yarn.lock
  presets/fireworks/yarn.lock
  presets/fountain/yarn.lock
  presets/links/yarn.lock
  presets/seaAnemone/yarn.lock
  presets/snow/yarn.lock
  presets/stars/yarn.lock
  presets/triangles/yarn.lock
  shapes/bubble/yarn.lock
  shapes/heart/yarn.lock
  shapes/multiline-text/yarn.lock
  shapes/rounded-rect/yarn.lock
  shapes/spiral/yarn.lock
  updaters/gradient/yarn.lock
  updaters/orbit/yarn.lock
Labels: size/L

#3264 Update preset links
  README.md
Labels: size/S

#3331 Website updated
  website/404.html
  website/index.html
  website/js/demo.js
  website/samples/index.html
  website/samples/presets/bigCircles.html
  website/samples/presets/bubbles.html
  website/samples/presets/confetti.html
  website/samples/presets/fire.html
  website/samples/presets/firefly.html
  website/samples/presets/fireworks.html
  website/samples/presets/fountain.html
  website/samples/presets/links.html
  website/samples/presets/seaAnemone.html
  website/samples/presets/snow.html
  website/samples/presets/stars.html
  website/samples/presets/triangles.html
Labels: size/L

#3332 Fix publish angular component
  components/angular/package.json
Labels: size/XS

#3352 Update Svelte event handling snippets
  components/svelte/README.md
  components/svelte/traduction/README.mn.md
  presets/bigCircles/README.md
  presets/bubbles/README.md
  presets/confetti/README.md
  presets/fire/README.md
  presets/firefly/README.md
  presets/fireworks/README.md
  presets/fountain/README.md
  presets/links/README.md
  presets/seaAnemone/README.md
  presets/snow/README.md
  presets/stars/README.md
  presets/triangles/README.md
Labels: size/M

#3368 Add typings for Svelte component
  components/svelte/package.json
  components/svelte/src/index.d.ts
Labels: size/S
