Repository tsparticles/tsparticles, pull requests merged in 2022-04, with the labels that each got.

#3118 Updated README links
  components/react/README.md
Labels: size/S

#3771 Revert "build(deps-dev): bump @parcel/transformer-sass from 2.3.2 to 2.4.1"
  yarn.lock
Labels: size/L

#3772 Branch cleanup
  .github/dependabot.yml
  .github/workflows/nodejs.yml
  renovate.json
Labels: size/XS

#3902 Update renovate.json
  renovate.json
Labels: size/XS

#3949 [Snyk] Upgrade: @angular/animations, @angular/common, @angular/compiler, @angular/core, @angular/forms, @angular/platform-browser, @angular/platform-browser-dynamic, @angular/router
  demo/angular/package.json
  demo/angular/yarn.lock
Labels: size/M

#3979 [Snyk] Upgrade @angular/common from 13.3.1 to 13.3.2
  components/angular/package.json
  components/angular/yarn.lock
Labels: size/S
