Repository tsparticles/tsparticles, pull requests merged in 2022-07, with the labels that each got.

#4368 build: changed pr template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/workflows/nodejs.yml
Labels: size/M

#4372 fix(readme): fix error 404 links
  components/inferno/README.md
  components/inferno/traduction/README.de.md
  components/inferno/traduction/README.mn.md
  components/inferno/traduction/README.nl.md
  components/inferno/traduction/README.pt-br.md
  components/inferno/traduction/README.ru.md
  components/preact/README.md
  components/preact/traduction/README.de.md
  components/preact/traduction/README.es.md
  components/preact/traduction/README.id.md
  components/preact/traduction/README.mn.md
  components/preact/traduction/README.nl.md
  components/preact/traduction/README.pt-br.md
  components/preact/traduction/README.ru.md
  components/react/README.md
  components/react/traduction/README.de.md
  components/react/traduction/README.es.md
  components/react/traduction/README.id.md
  components/react/traduction/README.mn.md
  components/react/traduction/README.nl.md
  components/react/traduction/README.pt-br.md
  components/react/traduction/README.ru.md
  components/solid/README.md
  components/solid/traduction/README.es.md
  components/solid/traduction/README.mn.md
  engine/traduction/README.es.md
  engine/traduction/README.id.md
  engine/traduction/README.nl.md
  engine/traduction/README.pt-br.md
  engine/traduction/README.ru.md
  traduction/README.de.md
  traduction/README.es.md
  traduction/README.hi.md
  traduction/README.id.md
  traduction/README.nl.md
  traduction/README.pt-br.md
  traduction/README.ru.md
Labels: size/M

#4373 Update nodejs.yml
  .github/workflows/nodejs.yml
Labels: size/S

#4374 Update nodejs.yml
  .github/workflows/nodejs.yml
Labels: size/XS

#4516 [Snyk] Upgrade preact from 10.8.1 to 10.8.2
  demo/preact/package.json
  demo/preact/yarn.lock
Labels: size/S
