Repository tsparticles/tsparticles, pull requests merged in 2022-10, with the labels that each got.

#4749 Small updates
  .github/workflows/nodejs.yml
  components/vue-alt/package.json
  components/vue/package.json
  components/vue3-alt/package.json
  components/vue3/package.json
  demo/vue/package.json
  pnpm-lock.yaml
Labels: size/XXL

#4746 Suggest french translation for vue3 readme
  components/vue3/traduction/README.fr.md
Labels: size/L

#4750 Missing dev commits
  components/vue3/traduction/README.fr.md
Labels: size/L

#4751 Suggest french translation for vue readme
  components/vue-alt/traduction/README.fr.md
  components/vue/traduction/README.fr.md
  components/vue3-alt/traduction/README.fr.md
Labels: size/L

#4756 Update integration links in demo
  websites/particles.js.org/samples/index.html
Labels: size/S

#4774 Fixed typos in Readme file
  README.md
Labels: size/S

#4779 Update README.md
  README.md
Labels: size/XS

#4782 Update README.md
  README.md
Labels: size/XS

#4798 edit README.tr
  traduction/README.tr.md
Labels: size/S
