Repository tsparticles/tsparticles, pull requests merged in 2022-03, with the labels that each got.

#3486 Updated website descriptions
  website/404.html
  website/index.html
  website/samples/index.html
  website/samples/presets/bigCircles.html
  website/samples/presets/bubbles.html
  website/samples/presets/confetti.html
  website/samples/presets/fire.html
  website/samples/presets/firefly.html
  website/samples/presets/fireworks.html
  website/samples/presets/fountain.html
  website/samples/presets/index.html
  website/samples/presets/links.html
  website/samples/presets/seaAnemone.html
  website/samples/presets/snow.html
  website/samples/presets/stars.html
  website/samples/presets/triangles.html
  website/sitemap.xml
Labels: size/XXL

#3504 Repo updates
  CONTRIBUTING.md
  demo/ionic/package.json
  demo/ionic/yarn.lock
Labels: size/S

#3505 fix: do not load particles on the Node.js side and make its loading cancellable
  components/angular/projects/ng-particles/README.md
  components/angular/projects/ng-particles/src/lib/ng-particles.component.ts
  components/angular/projects/ng-particles/src/lib/ng-particles.module.ts
Labels: size/M

#3528 Removed useless console.log in Canvas.ts
  engine/src/Core/Canvas.ts
Labels: size/XS

#3600 Revert "chore(deps): update dependency npm-packlist to v4 (next)"
  package.json
  yarn.lock
Labels: size/S
