Repository tsparticles/tsparticles, pull requests merged in 2022-08, with the labels that each got.

#4479 Update missing docs and adding JS/TS support in React
  components/react/README.md
Labels: size/L

#4591 Update SECURITY.md
  SECURITY.md
Labels: size/S

#4598 Update SECURITY.md
  SECURITY.md
Labels: size/XS
